# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-01 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='이름', max_length=20)),
                ('title', models.CharField(db_column='제목', max_length=50)),
                ('text', models.TextField(db_column='내용', help_text='메모 내용은 150자 이내로 입력 가능합니다.', max_length=150)),
                ('update_date', models.DateTimeField()),
                ('Priority', models.BooleanField(db_column='중요')),
            ],
        ),
    ]
