# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-02 00:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memo_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memos',
            name='update_date',
        ),
    ]
