# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-02 04:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memo_app', '0002_remove_memos_update_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memos',
            old_name='Priority',
            new_name='priority',
        ),
    ]
