# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-02 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('memo_app', '0003_auto_20170302_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='memos',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
