# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-08 06:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memo_app', '0007_auto_20170303_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='memos',
            name='name_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
