# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-08 06:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memo_app', '0008_memos_name_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memos',
            name='name',
        ),
    ]
