# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-10 00:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memo_app', '0009_remove_memos_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='memos',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
